[package]
name = "t_xkernel"
version = "0.1.0"
authors = ["Mnimi Aionios <mechild02@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
linked_list_allocator = "*"
slab_allocator = "0.3.1"
spin = "0.7.0"
spinning_top = "0.2.2"
volatile = "0.4.2"

[lib]
name = "t_xkernel_core"
path = "lib.rs"
