# .cargo/config.toml

[target."target.json"]
rustflags = ['-Clink-arg=-Tvirt.lds']

[build]
target = "target.json"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
