# .cargo/config.toml

[target."target.json"]
rustflags = [
  "-C", "link-arg=-Tmemory.ld",
  "-C", "link-arg=-Tlink.ld",
]

[build]
target = "target.json"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
